/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorting;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.PrintStream;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Nugraha
 */
public class bubble extends javax.swing.JFrame {
    
    int xMouse;
    int yMouse;
    int timeRun = 0;

    /**
     * Creates new form Home
     */
    public bubble() {
        initComponents();
        setLocationRelativeTo(this);
        fixit();
        
    }
    
    public void fixit() {
        p6.setVisible(false);
        p5.setVisible(false);
        p4.setVisible(false);
        p3.setVisible(false);
        tfx5.requestFocus();
        sort3.setVisible(false);
        sort4.setVisible(false);
        sort5.setVisible(false);
        sort6.setVisible(false);
        
        setBorder2(sort2);
        resetColor(sort2);
        setBorder2(sort3);
        resetColor(sort3);
        setBorder2(sort4);
        resetColor(sort4);
        setBorder2(sort5);
        resetColor(sort5);
        setBorder2(sort6);
        resetColor(sort6);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        Mini = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        page = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        p6 = new javax.swing.JPanel();
        tfx1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        p5 = new javax.swing.JPanel();
        tfx2 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        p4 = new javax.swing.JPanel();
        tfx3 = new javax.swing.JTextField();
        tf11 = new javax.swing.JTextField();
        tf12 = new javax.swing.JTextField();
        tf13 = new javax.swing.JTextField();
        p3 = new javax.swing.JPanel();
        tfx4 = new javax.swing.JTextField();
        tf14 = new javax.swing.JTextField();
        tf15 = new javax.swing.JTextField();
        p2 = new javax.swing.JPanel();
        tfx5 = new javax.swing.JTextField();
        tf16 = new javax.swing.JTextField();
        sort2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sort3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sort4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        sort5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        sort6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        test = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(102, 51, 255));
        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleMouseDragged(evt);
            }
        });
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X ");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        title.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 50, 50));

        Mini.setBackground(new java.awt.Color(122, 72, 221));
        Mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Minimize_Window_25px_2.png"))); // NOI18N
        Mini.setBorder(null);
        Mini.setBorderPainted(false);
        Mini.setContentAreaFilled(false);
        Mini.setFocusPainted(false);
        Mini.setFocusable(false);
        Mini.setRequestFocusEnabled(false);
        Mini.setVerifyInputWhenFocusTarget(false);
        Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniMouseClicked(evt);
            }
        });
        title.add(Mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 50, 50));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bubble Sort");
        title.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 520, 90));

        jButton1.setBackground(new java.awt.Color(102, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        title.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 138));

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 255)));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb1.setBackground(new java.awt.Color(255, 255, 254));
        cb1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        cb1.setForeground(new java.awt.Color(122, 71, 221));
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        page.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 150, 30));

        jSeparator1.setBackground(new java.awt.Color(122, 71, 221));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 10, 410));

        jSeparator2.setBackground(new java.awt.Color(122, 71, 221));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        page.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 10, 410));

        p6.setBackground(new java.awt.Color(255, 255, 255));
        p6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 2, true), " Input your data ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(122, 71, 221))); // NOI18N
        p6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfx1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tfx1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfx1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tfx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfx1ActionPerformed(evt);
            }
        });
        tfx1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfx1KeyTyped(evt);
            }
        });
        p6.add(tfx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 60));

        tf3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf3KeyTyped(evt);
            }
        });
        p6.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 60, 60));

        tf4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tf4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        tf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf4KeyTyped(evt);
            }
        });
        p6.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 60, 60));

        tf5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tf5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        tf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf5KeyTyped(evt);
            }
        });
        p6.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 60, 60));

        tf6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tf6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        tf6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf6KeyTyped(evt);
            }
        });
        p6.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 60, 60));

        tf1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });
        p6.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 60));

        page.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 210));

        p5.setBackground(new java.awt.Color(255, 255, 255));
        p5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 2, true), " Insert your data ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18), new java.awt.Color(122, 71, 221))); // NOI18N
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfx2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tfx2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfx2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tfx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfx2ActionPerformed(evt);
            }
        });
        tfx2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfx2KeyTyped(evt);
            }
        });
        p5.add(tfx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 60, 60));

        tf7.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        tf7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf7KeyTyped(evt);
            }
        });
        p5.add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 60, 60));

        tf8.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });
        tf8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf8KeyTyped(evt);
            }
        });
        p5.add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 60, 60));

        tf9.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf9ActionPerformed(evt);
            }
        });
        tf9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf9KeyTyped(evt);
            }
        });
        p5.add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 60, 60));

        tf10.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf10ActionPerformed(evt);
            }
        });
        tf10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf10KeyTyped(evt);
            }
        });
        p5.add(tf10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 60, 60));

        page.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 210));

        p4.setBackground(new java.awt.Color(255, 255, 255));
        p4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 2, true), " Insert your data ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18), new java.awt.Color(122, 71, 221))); // NOI18N
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfx3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tfx3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfx3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tfx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfx3ActionPerformed(evt);
            }
        });
        tfx3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfx3KeyTyped(evt);
            }
        });
        p4.add(tfx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, 60));

        tf11.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf11ActionPerformed(evt);
            }
        });
        tf11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf11KeyTyped(evt);
            }
        });
        p4.add(tf11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 60));

        tf12.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf12.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf12ActionPerformed(evt);
            }
        });
        tf12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf12KeyTyped(evt);
            }
        });
        p4.add(tf12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 60, 60));

        tf13.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf13.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf13ActionPerformed(evt);
            }
        });
        tf13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf13KeyTyped(evt);
            }
        });
        p4.add(tf13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, 60));

        page.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 210));

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 2, true), " Insert your data ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18), new java.awt.Color(122, 71, 221))); // NOI18N
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfx4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tfx4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfx4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tfx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfx4ActionPerformed(evt);
            }
        });
        tfx4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfx4KeyTyped(evt);
            }
        });
        p3.add(tfx4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 60));

        tf14.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf14.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf14ActionPerformed(evt);
            }
        });
        tf14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf14KeyTyped(evt);
            }
        });
        p3.add(tf14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 60, 60));

        tf15.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf15.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf15ActionPerformed(evt);
            }
        });
        tf15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf15KeyTyped(evt);
            }
        });
        p3.add(tf15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 60, 60));

        page.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 210));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 2, true), " Insert your data ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18), new java.awt.Color(122, 71, 221))); // NOI18N
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfx5.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tfx5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfx5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tfx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfx5ActionPerformed(evt);
            }
        });
        tfx5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfx5KeyTyped(evt);
            }
        });
        p2.add(tfx5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 60));

        tf16.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tf16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf16.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 1, true), "2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        tf16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf16ActionPerformed(evt);
            }
        });
        tf16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf16KeyTyped(evt);
            }
        });
        p2.add(tf16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 60, 60));

        page.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 210));

        sort2.setBackground(new java.awt.Color(255, 255, 255));
        sort2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sort2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sort2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sort2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sort2MouseExited(evt);
            }
        });
        sort2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sorting");
        sort2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 40));

        page.add(sort2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 60));

        sort3.setBackground(new java.awt.Color(255, 255, 255));
        sort3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sort3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sort3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sort3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sort3MouseExited(evt);
            }
        });
        sort3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Jokerman", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Sorting");
        sort3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 40));

        page.add(sort3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 60));

        sort4.setBackground(new java.awt.Color(255, 255, 255));
        sort4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sort4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sort4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sort4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sort4MouseExited(evt);
            }
        });
        sort4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Jokerman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sorting");
        sort4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 40));

        page.add(sort4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 60));

        sort5.setBackground(new java.awt.Color(255, 255, 255));
        sort5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sort5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sort5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sort5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sort5MouseExited(evt);
            }
        });
        sort5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Jokerman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sorting");
        sort5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 40));

        page.add(sort5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 60));

        sort6.setBackground(new java.awt.Color(255, 255, 255));
        sort6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        sort6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sort6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sort6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sort6MouseExited(evt);
            }
        });
        sort6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Jokerman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Sorting");
        sort6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 40));

        page.add(sort6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 60));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 71, 221));
        jLabel4.setText("Data");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, 30));

        p7.setBackground(new java.awt.Color(255, 255, 255));
        p7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 71, 221), 2, true), " Result ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(122, 71, 221))); // NOI18N
        p7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        test.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        test.setForeground(new java.awt.Color(122, 71, 221));
        test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p7.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 410, 130));

        page.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 430, 210));

        jPanel2.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, 1050, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void doexit()
    {
        int confirm = JOptionPane.showConfirmDialog(null, 
                "Do You Want To Exit?", "Close The Applicatin",
                JOptionPane.YES_NO_OPTION);    
        
        if (confirm == JOptionPane.YES_OPTION){
        System.exit(0);
    }
    
    }
    
    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        doexit();
    }//GEN-LAST:event_ExitMouseClicked

    private void MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_MiniMouseClicked

    private void titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_titleMouseDragged

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleMousePressed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tfx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfx1ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf6ActionPerformed

    private void tfx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfx2ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf8ActionPerformed

    private void tf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf9ActionPerformed

    private void tf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf10ActionPerformed

    private void tfx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfx3ActionPerformed

    private void tf11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf11ActionPerformed

    private void tf12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf12ActionPerformed

    private void tf13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf13ActionPerformed

    private void tfx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfx4ActionPerformed

    private void tf14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf14ActionPerformed

    private void tf15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf15ActionPerformed

    private void tfx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfx5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfx5ActionPerformed

    private void tf16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf16ActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
        if(cb1.getSelectedItem() == "2") {
            p2.setVisible(true);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            
            tfx5.requestFocus();
            
        sort2.setVisible(true);
        sort3.setVisible(false);
        sort4.setVisible(false);
        sort5.setVisible(false);
        sort6.setVisible(false);
        
        reset();
        } else if (cb1.getSelectedItem() == "3") {
            p3.setVisible(true);
            p2.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            
            tfx4.requestFocus();
        
        sort2.setVisible(false);
        sort3.setVisible(true);
        sort4.setVisible(false);
        sort5.setVisible(false);
        sort6.setVisible(false);
        
        reset();
        
            } else if (cb1.getSelectedItem() == "4") {
            p4.setVisible(true);
            p2.setVisible(false);
            p3.setVisible(false);
            p5.setVisible(false);
            p6.setVisible(false);
            
            tfx3.requestFocus();
            
        sort2.setVisible(false);
        sort3.setVisible(false);
        sort4.setVisible(true);
        sort5.setVisible(false);
        sort6.setVisible(false);
        
        reset();
        
            } else if (cb1.getSelectedItem() == "5") {
            p5.setVisible(true);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p6.setVisible(false);
            
            tfx2.requestFocus();
            
        sort2.setVisible(false);
        sort3.setVisible(false);
        sort4.setVisible(false);
        sort5.setVisible(true);
        sort6.setVisible(false);
        
        reset();
            } else if (cb1.getSelectedItem() == "6") {
            p6.setVisible(true);
            p2.setVisible(false);
            p3.setVisible(false);
            p4.setVisible(false);
            p5.setVisible(false);
            
            tfx1.requestFocus();
            
        sort2.setVisible(false);
        sort3.setVisible(false);
        sort4.setVisible(false);
        sort5.setVisible(false);
        sort6.setVisible(true);
        
        reset();
        }
    }//GEN-LAST:event_cb1ItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void sort2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort2MouseClicked
        // TODO add your handling code here:
      if(tfx5.getText().equals("") || tf16.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null,"Please input your data!","Error",JOptionPane.ERROR_MESSAGE);   
        } 
      else 
      {
        int a1 = Integer.parseInt(tfx5.getText());
        int a2 =Integer.parseInt(tf16.getText());
        int[] data = {a1, a2};
        
        int dataLength = data.length;
        int n = 0;
        while(n < dataLength) {
            for(int i=1; i<dataLength; i++){
                if(data[i-1] > data[i]){
                    int temp = data[i];
                    data[i] = data[i-1];
                    data[i-1] = temp;
                    
                }
            }
            n++;
        }
        
        for(int j = 0; j < data.length; j++) {
            System.out.print(data[j] + " ");
            test.setText(String.valueOf(data[0] + " - " +data[1]));
                    
            
        }
        }
      System.out.println(" ");
    }//GEN-LAST:event_sort2MouseClicked

    
    
    private void sort2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort2MouseEntered
        // TODO add your handling code here:
        setColorTF(jLabel12);
        setColor(sort2);
        setBorder2(sort2);
    }//GEN-LAST:event_sort2MouseEntered

    private void sort2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort2MouseExited
        // TODO add your handling code here:
        resetColor(sort2);
        resetColorTF(jLabel12);
    }//GEN-LAST:event_sort2MouseExited

    private void sort3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort3MouseClicked
        // TODO add your handling code here:
        if(tfx4.getText().equals("") || tf14.getText().equals("") || tf15.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null,"Please input your data!","Error",JOptionPane.ERROR_MESSAGE);   
        } 
      else 
      {
        int a1 = Integer.parseInt(tfx4.getText());
        int a2 =Integer.parseInt(tf14.getText());
        int a3 =Integer.parseInt(tf15.getText());
        int[] data = {a1, a2, a3};
        
        int dataLength = data.length;
        int n = 0;
        while(n < dataLength) {
            for(int i=1; i<dataLength; i++){
                if(data[i-1] > data[i]){
                    int temp = data[i];
                    data[i] = data[i-1];
                    data[i-1] = temp;
                     
                }
            }
            n++;
        }
        
        for(int j = 0; j < data.length; j++) {
            
            System.out.print(data[j] + " ");
            test.setText(String.valueOf(data[0] + " - " +data[1] + " - " + data[2]));
            
        }
        }
        System.out.println(" ");
    }//GEN-LAST:event_sort3MouseClicked

    private void sort3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort3MouseEntered
        // TODO add your handling code here:
        setColorTF(jLabel13);
        setColor(sort3);
        setBorder2(sort3);
    }//GEN-LAST:event_sort3MouseEntered

    private void sort3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort3MouseExited
        // TODO add your handling code here:
        resetColor(sort3);
        resetColorTF(jLabel13);
    }//GEN-LAST:event_sort3MouseExited

    private void sort4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort4MouseClicked
        // TODO add your handling code here:
        if(tfx3.getText().equals("") || tf11.getText().equals("") || tf12.getText().equals("") || tf13.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null,"Please input your data!","Error",JOptionPane.ERROR_MESSAGE);   
        } 
      else 
      {
        int a1 =Integer.parseInt(tfx3.getText());
        int a2 =Integer.parseInt(tf11.getText());
        int a3 =Integer.parseInt(tf12.getText());
        int a4 =Integer.parseInt(tf13.getText());
        int[] data = {a1, a2, a3, a4};
        
        int dataLength = data.length;
        int n = 0;
        while(n < dataLength) {
            for(int i=1; i<dataLength; i++){
                if(data[i-1] > data[i]){
                    int temp = data[i];
                    data[i] = data[i-1];
                    data[i-1] = temp;
                }
            }
            n++;
        }
        
        for(int j = 0; j < data.length; j++) {
            System.out.print(data[j] + " ");
            test.setText(String.valueOf(data[0] + " - " +data[1] + " - " + data[2] + " - " + data[3]));
        }
        }
        System.out.println(" ");
    }//GEN-LAST:event_sort4MouseClicked

    private void sort4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort4MouseEntered
        // TODO add your handling code here:
        setColorTF(jLabel14);
        setColor(sort4);
        setBorder2(sort4);
    }//GEN-LAST:event_sort4MouseEntered

    private void sort4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort4MouseExited
        // TODO add your handling code here:
        resetColor(sort4);
        resetColorTF(jLabel14);
    }//GEN-LAST:event_sort4MouseExited

    private void sort5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort5MouseClicked
        // TODO add your handling code here:
        if(tfx2.getText().equals("") || tf7.getText().equals("") || tf8.getText().equals("") || tf9.getText().equals("") || tf10.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null,"Please input your data!","Error",JOptionPane.ERROR_MESSAGE);   
        } 
      else 
      {
        int a1 =Integer.parseInt(tfx2.getText());
        int a2 =Integer.parseInt(tf7.getText());
        int a3 =Integer.parseInt(tf8.getText());
        int a4 =Integer.parseInt(tf9.getText());
        int a5 =Integer.parseInt(tf10.getText());
        int[] data = {a1, a2, a3, a4, a5};
        
        int dataLength = data.length;
        int n = 0;
        while(n < dataLength) {
            for(int i=1; i<dataLength; i++){
                if(data[i-1] > data[i]){
                    int temp = data[i];
                    data[i] = data[i-1];
                    data[i-1] = temp;
                }
            }
            n++;
        }
        
        for(int j = 0; j < data.length; j++) {
            System.out.print(data[j] + " ");
            test.setText(String.valueOf(data[0] + " - " +data[1] + " - " + data[2] + " - " + data[3] + " - " + data[4]));
        }
        }
        System.out.println(" ");
    }//GEN-LAST:event_sort5MouseClicked

    private void sort5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort5MouseEntered
        // TODO add your handling code here:
        setColorTF(jLabel15);
        setColor(sort5);
        setBorder2(sort5);
    }//GEN-LAST:event_sort5MouseEntered

    private void sort5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort5MouseExited
        // TODO add your handling code here:
        resetColor(sort5);
        resetColorTF(jLabel15);
    }//GEN-LAST:event_sort5MouseExited

    public void reset() {
        tfx1.setText("");
        tfx2.setText("");
        tfx3.setText("");
        tfx4.setText("");
        tfx5.setText("");
        tf1.setText("");
        tf3.setText("");
        tf4.setText("");
        tf5.setText("");
        tf6.setText("");
        tf7.setText("");
        tf8.setText("");
        tf9.setText("");
        tf10.setText("");
        tf11.setText("");
        tf12.setText("");
        tf13.setText("");
        tf14.setText("");
        tf15.setText("");
        tf16.setText("");
        test.setText("");
    }
    
    private void sort6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort6MouseClicked
        // TODO add your handling code here:
                if(tfx1.getText().equals("") || tf1.getText().equals("") || tf3.getText().equals("") || tf4.getText().equals("") || tf5.getText().equals("")  || tf6.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null,"Please input your data!","Error",JOptionPane.ERROR_MESSAGE);   
        } 
      else 
      {
        int a1 =Integer.parseInt(tfx1.getText());
        int a2 =Integer.parseInt(tf1.getText());
        int a3 =Integer.parseInt(tf3.getText());
        int a4 =Integer.parseInt(tf4.getText());
        int a5 =Integer.parseInt(tf5.getText());
        int a6 =Integer.parseInt(tf6.getText());
        int[] data = {a1, a2, a3, a4, a5,a6};
        
        int dataLength = data.length;
        int n = 0;
        while(n < dataLength) {
            for(int i=1; i<dataLength; i++){
                if(data[i-1] > data[i]){
                    int temp = data[i];
                    data[i] = data[i-1];
                    data[i-1] = temp;
                }
            }
            n++;
        }
        
        for(int j = 0; j < data.length; j++) {
            System.out.print(data[j] + " ");
            test.setText(String.valueOf(data[0] + " - " +data[1] + " - " + data[2] + " - " + data[3] + " - " + data[4] + " - " + data[5]));
        }
        }
        System.out.println(" ");
    }//GEN-LAST:event_sort6MouseClicked

    private void sort6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort6MouseEntered
        // TODO add your handling code here:
        setColorTF(jLabel16);
        setColor(sort6);
        setBorder2(sort6);
    }//GEN-LAST:event_sort6MouseEntered

    private void sort6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sort6MouseExited
        // TODO add your handling code here:
        resetColor(sort6);
        resetColorTF(jLabel16);
    }//GEN-LAST:event_sort6MouseExited

    private void tfx1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx1KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tfx1KeyTyped

    private void tf3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf3KeyTyped

    private void tf4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf4KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf4KeyTyped

    private void tf5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf5KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf5KeyTyped

    private void tf6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf6KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf6KeyTyped

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf1KeyTyped

    private void tfx2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx2KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tfx2KeyTyped

    private void tf8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf8KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf8KeyTyped

    private void tf10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf10KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf10KeyTyped

    private void tf7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf7KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf7KeyTyped

    private void tf9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf9KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf9KeyTyped

    private void tfx3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx3KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tfx3KeyTyped

    private void tf11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf11KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf11KeyTyped

    private void tf12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf12KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf12KeyTyped

    private void tf13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf13KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf13KeyTyped

    private void tfx4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx4KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tfx4KeyTyped

    private void tf14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf14KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf14KeyTyped

    private void tf15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf15KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf15KeyTyped

    private void tfx5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfx5KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tfx5KeyTyped

    private void tf16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf16KeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        
        }
    }//GEN-LAST:event_tf16KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Bubbleintro ob = new Bubbleintro();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

     public void setLblColor (JPanel lbl)
    {
    lbl.setBackground(new Color(122,72,221));
    }
    
    public void resetLblColor (JPanel lbl)
    {
    lbl.setBackground(new Color(54,33,89));
    }
    
    
public void setColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(112, 71, 221));
    }

public void resetColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(240, 240, 240));
    }

public void resetColor2(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(54,33,89));
    }
      
    
    public void setBorder2(JPanel panel)
    {
    panel.setBorder(new LineBorder(Color.white,30,true));
    }    
    
    public void resetBorder(JPanel panel)
    {
    panel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }
    
    public void setColorTF(JLabel label)
    {
        label.setForeground(new java.awt.Color(112, 71, 221));
    }

public void resetColorTF(JLabel label)
    {
        label.setForeground(new java.awt.Color(200,200,200));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bubble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bubble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bubble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bubble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bubble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton Mini;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel page;
    private javax.swing.JPanel sort2;
    private javax.swing.JPanel sort3;
    private javax.swing.JPanel sort4;
    private javax.swing.JPanel sort5;
    private javax.swing.JPanel sort6;
    private javax.swing.JLabel test;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf13;
    private javax.swing.JTextField tf14;
    private javax.swing.JTextField tf15;
    private javax.swing.JTextField tf16;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    private javax.swing.JTextField tfx1;
    private javax.swing.JTextField tfx2;
    private javax.swing.JTextField tfx3;
    private javax.swing.JTextField tfx4;
    private javax.swing.JTextField tfx5;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
